### ISSUE TITLE
Cannot find caffe.* in fcn_tracker.m (follow the instruction compiling)

### ISSUE THREAD

**Issue by jeremythu** [myfavouritekk/T-CNN#1]
Following the instruction, I compiled matcaffe for caffe_fcn, but it can not pass the "Demo->4,Tubelet tracking and re-scoring". 

It always stopped at fcn_tracker.m for "can not find caffe or caffe.* ".  I haven't meet this problem in original FCN tracking.

Do I need to addpath to change matlab work path? anyone can give a help?

**Comment by myfavouritekk** [comment]
Right, please copy the complied `+caffe` folder in the `caffe_fcn/matlab` to the directory of the tracker. I will write a instruction on the tracker repository  to help make sure the installation is valid.

**Comment by myfavouritekk** [comment]
Fixed. Please follow the instructions on https://github.com/myfavouritekk/FCNT/tree/T-CNN.
