### ISSUE TITLE
Need window_size_7_time_step_1_top_ratio_0.000300_top_bonus_0.400000_optflow_max_pooling to receate the demo

### ISSUE THREAD

**Issue by jeremythu** [myfavouritekk/T-CNN#2]
It seems there is no window_size_7_time_step_1_top_ratio_0.000300_top_bonus_0.400000_optflow_max_pooling
to recreate the demo

Do I miss something?

**Comment by myfavouritekk** [comment]
The `window_size_7_time_step_1_top_ratio_0.000300_top_bonus_0.400000_optflow_max_pooling` directory is generated after the `spatial max-pooling` in the demo. Maybe something wrong with the tracking? Have you successfully compiled the tracker?

**Comment by jeremythu** [comment]
This directory is ok~ I thought it's an intermediate training results or something......you can close this issue now ~ thanks a lot~
