### ISSUE TITLE
How to get the tubelet visulaization as good as presented in your ILSVRC 2015 presentation?

### ISSUE THREAD

**Issue by ronakgupta** [myfavouritekk/T-CNN#3]
I ran the demo. After the spatial max-pooling, there are more than one tubelet box appearing on the airplane. I am running the code on Linux platform.

Also, please add commands to run temporal convolution and rescoring

**Comment by myfavouritekk** [comment]
@ronakgupta Thank you for your feedback. The temporal convolution is not used in this project (but the CVPR paper), and will be included soon in the [vdetlib](https://github.com/myfavouritekk/vdetlib) repository.

**Comment by myfavouritekk** [comment]
@ronakgupta Hi, did you send me an email the other day? Somehow your email address is unknown that causes a delivery failure. Please check your email address. Thanks.

**Comment by ronakgupta** [comment]
@myfavouritekk Ya, I have again sent the mail. Thanks.

**Comment by myfavouritekk** [comment]
@ronakgupta still not working, do you have a gmail or something?

**Comment by ronakgupta** [comment]
@myfavouritekk  Ok. Please mail me to ronakgupta143@gmail.com
