### ISSUE TITLE
A error in demo step.2

### ISSUE THREAD

**Issue by a980410** [myfavouritekk/T-CNN#6]
I meet a error when I test the demo step.2 "Generate optical flow for the videos"
----------------------------------------------------------------------------------------------------------
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence the citation notice: run 'parallel --citation'.

Traceback (most recent call last):
  File "tools/data_proc/gen_optical_flow.py", line 3, in <module>
    import cv2
ImportError: No module named cv2
----------------------------------------------------------------------------------------------------------
ubuntu14.04    Python2.7   MATLAB2015a
Caffe and FCN-tracker are fine.

By the way, how to deal with "matutils" ? I put it in $TCNN_ROOT,is it right?

**Comment by myfavouritekk** [comment]
1. For `GNU Parallel` simply type `parallel --citation` and follow the instructions.
2. ImportError: You haven't installed OpenCV python package. Please use pip to installed it.
3. put the `matutils` folder in the `External`, or simply `addpath` in the Matlab code.

**Comment by a980410** [comment]
Thank you. It worked without error.
Looking forward to vdetlib.
