### ISSUE TITLE
question about "scores" in the input

### ISSUE THREAD

**Issue by cemysf** [myfavouritekk/T-CNN#8]
Hi, I'd like to try a different video for testing, how can I produce .mat files for scores folder?

**Comment by myfavouritekk** [comment]
@cemysf You can use any of the static detection framework to produce these scores, for example, RCNN, Fast RCNN or Faster RCNN.

**Comment by cemysf** [comment]
ok thanks,  is there any script in this project for creating .mat files from box coordinates and scores for each frame?

**Comment by myfavouritekk** [comment]
@cemysf Since still-image detection part is not the focus of this project, we did not include it.
