### ISSUE TITLE
why still image detection score is not between [0,1]?

### ISSUE THREAD

**Issue by wwwanghao** [myfavouritekk/T-CNN#9]
dear @myfavouritekk, Still image detection outputs are bounding box and probability corresponding to different classes, and thus the scores should between [0,1]. Why scores in your example data is not? 

Another question
Bounding boxes output from Faster RCNN or other Detecion Program shouldn't be as many as your example data. Did you keep most of the output bounding boxes with a low score threshold? Or the bounding boxes just come from RPN output?

Thank you!

**Comment by myfavouritekk** [comment]
Hi @wwwanghao, the still image detection results were generated by RCNN framework with SVM classifier for each class. SVM scores are not bounded within [0,1]. In addition, we have an ensemble of 5 models, and the scores are the sum of all the models. The details of the classifier are in the tech report.

For the number of boxes, we used the selective search and edge boxes to generate proposals and trained a "weak" classifier to eliminate low-confidence proposals. You can also find some details in the tech report.
